all:
	g++ -std=c++11 -o ./main ./main.cpp
	g++ -std=c++11 -o ./tester ./tester.cpp
	g++ -std=c++11 -o ./bigmain ./bigmain.cpp

bigmain:
	g++ -std=c++11 -o ./bigmain ./bigmain.cpp

main:
	g++ -std=c++11 -o ./main ./main.cpp

tester:
	g++ -std=c++11 -o ./tester ./tester.cpp